export const FETCH_RESTAURANTS = 'FETCH_RESTAURANTS';
export const FETCH_RESTAURANTS_SUCCESS = "FETCH_RESTAURANT_SUCCESS";
export const FETCH_RESTAURANTS_FAIL = "FETCH_RESTAURANT_FAIL";
export const SORT_RESTAURANTS = 'SORT_RESTAURANTS';
export const DISPLAY_RESTAURANTS = 'DISPLAY_RESTAURANTS';
export const VIEW_RESTAURANT = 'VIEW_RESTAURANT';