import { viewRestaurant } from './viewRestaurant'
import { displayRestaurants } from './displayRestaurants'
import { getLocation } from './getLocation'
import { getRestaurants } from './getRestaurants'
import { sortRestaurants } from './sortRestaurants'